from docx import Document
from docx.shared import Inches

# Create Internal Document
internal_doc = Document()
internal_doc.add_heading('Internal Report: HURTX-2024-0456', 0)

internal_doc.add_heading('Claim Details', level=1)
internal_doc.add_paragraph('Claim ID: HURTX-2024-0456')
internal_doc.add_paragraph('Claimant: Contoso Electronics Inc.')
internal_doc.add_paragraph('Date Filed: January 27, 2025')
internal_doc.add_paragraph('Incident Type: Hurricane Alicia')
internal_doc.add_paragraph('Incident Date: May 15, 2024')
internal_doc.add_paragraph('Store Location: Contoso Electronics #TX-230, 1125 Main Street, Houston, TX 77002')
internal_doc.add_paragraph('Contact: Gabriel Allen (Store Manager)')

internal_doc.add_heading('Damage Assessment', level=1)
internal_doc.add_paragraph('Types of Damage:')
internal_doc.add_paragraph('- Severe roof damage and water intrusion on the south side.')
internal_doc.add_paragraph('- Flooded inventory storage with electronics submerged.')
internal_doc.add_paragraph('- Electrical panels shorted due to water ingress.')
internal_doc.add_paragraph('- Potential structural compromise in the south wing support beams.')
internal_doc.add_paragraph('Preliminary Damage Estimates:')
internal_doc.add_paragraph('Inventory Loss: $380,000')
internal_doc.add_paragraph('Structural Damage: $200,000')
internal_doc.add_paragraph('Equipment Replacement: $160,000')
internal_doc.add_paragraph('Business Interruption: TBD.')

internal_doc.add_heading('Mitigation Steps Taken', level=1)
internal_doc.add_paragraph('- Secure site and prevent unauthorized entry.')
internal_doc.add_paragraph('- Engage emergency restoration team for water extraction.')
internal_doc.add_paragraph('- Move salvageable inventory to upper floors.')
internal_doc.add_paragraph('- Install temporary roof patch.')

internal_doc.add_heading('Policy Coverage Details', level=1)
internal_doc.add_paragraph('Policy Number: CP-TX-2024087')
internal_doc.add_paragraph('Period: January 1, 2024 - December 31, 2024')
internal_doc.add_paragraph('Coverage:')
internal_doc.add_paragraph('- Hurricane/Wind Coverage: Included')
internal_doc.add_paragraph('- Flood Coverage: Included (Deductible: $50,000)')
internal_doc.add_paragraph('- Business Interruption: Included (sub-limit $500,000)')
internal_doc.add_paragraph('- Replacement Cost: Included')
internal_doc.add_paragraph('Total Insured Value: $2,000,000')
internal_doc.add_paragraph('Sublimits:')
internal_doc.add_paragraph('- Building Structure: Up to $1,000,000')
internal_doc.add_paragraph('- Business Property (Incl. Inventory): Up to $600,000')
internal_doc.add_paragraph('- Electronic Equipment: Up to $200,000')
internal_doc.add_paragraph('Deductibles:')
internal_doc.add_paragraph('- Hurricane/Wind: 5% of Total Insured Value ($100,000)')
internal_doc.add_paragraph('- Flood: $50,000')
internal_doc.add_paragraph('- Standard: $25,000')

internal_doc.add_heading('Weather Report', level=1)
internal_doc.add_paragraph('Storm: Hurricane Alicia')
internal_doc.add_paragraph('Category: 3')
internal_doc.add_paragraph('Max Sustained Winds: ~120 mph')
internal_doc.add_paragraph('Date: May 15, 2024')
internal_doc.add_paragraph('Impact on Houston:')
internal_doc.add_paragraph('- Landfall near Galveston, TX')
internal_doc.add_paragraph('- Severe conditions lasting 6-8 hours over Houston')
internal_doc.add_paragraph('- Sustained winds of 100-120 mph, gusts up to 130+ mph')
internal_doc.add_paragraph('Rainfall totaling 10-14 inches')
internal_doc.add_paragraph('Storm Surge: 8-10 feet along coastal areas')

internal_doc.add_heading('Damage Cost Breakdown', level=1)
internal_doc.add_picture('damage_cost_breakdown.png', width=Inches(5))

internal_doc.add_heading('Deductions Applied', level=1)
internal_doc.add_picture('deductions_applied.png', width=Inches(5))

internal_doc.add_heading('Risk Assessment Metrics', level=1)
internal_doc.add_picture('risk_assessment_metrics.png', width=Inches(5))

internal_doc.add_heading('Final Recommendation', level=1)
internal_doc.add_paragraph('Final Recommendation: Partial Approve')
internal_doc.add_paragraph('Rationale:')
internal_doc.add_paragraph('- Hurricane Alicia observed to have caused substantial damage consistent with the claim details.')
internal_doc.add_paragraph('- Policy provides coverage for hurricane/wind and flood damages, including business interruption.')
internal_doc.add_paragraph('- Deductibles applicable for hurricane/wind ($100,000) and flood ($50,000).')
internal_doc.add_paragraph('- Mitigation efforts were moderately effective but did not prevent all damages.')
internal_doc.add_paragraph('- Verification and detailed accounting required for business interruption losses and complete inventory losses.')
internal_doc.add_paragraph('- Pending professional structural engineer’s report for structural compromise confirmation.')

internal_doc.add_paragraph('Approved Amount: $640,000')
internal_doc.add_paragraph('Deductions:')
internal_doc.add_paragraph('- Hurricane/Wind Deductible: $100,000')
internal_doc.add_paragraph('- Flood Deductible: $50,000')

internal_doc.add_paragraph('Conditions:')
internal_doc.add_paragraph('- Provide detailed structural engineer’s report.')
internal_doc.add_paragraph('- Submit complete accounting for business interruption losses.')
internal_doc.add_paragraph('- Confirm all inventory losses with detailed assessment.')

internal_doc.save('report/HURTX-2024-0456_Internal.docx')